mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from webfront.views import home, contact, about, form, dyno, profile, full, u, duo
from rest_framework import routers
from rest_framework.routers import DefaultRouter
admin.autodiscover()
router = DefaultRouter()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
#    url(r'^contact/$', contact,name='contact'),
    url(r'^about/$', about, name='about'),
    url(r'^form/$',form, name='form'),
                          
#  Authenticated:
    url(r'^search/',dyno, name='search'),
    url(r'^full/',full),
#    url(r'^fullc/','webfront.views.fullc'),
    url(r'^u/',u),
#    url(r'^c/','webfront.views.c', name='cmv'),
    url(r'^accounts/profile/$', profile,name='profile'),
                                                             
# GIS
#   url(r'^map/$', 'webfront.views.imap', name='map'),
#   url(r'^imap/$', 'webfront.views.imap', name='imap'),
#   url(r'^pmap/$', 'webfront.views.pmap', name='pmap'),

## Rest API
   url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
   url(r'^', include('webfront.urls')),
                                                                                                  
## Admin
#   url(r'^admin/', include(admin.site.urls)),
   url(r'^', include(router.urls)),
   url(r'^duo_private/',duo),
   url(r'^accounts/', include('registration.auth_urls')),
   url(r'^accounts/', include('registration.backends.default.urls')),
        
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webfront/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import routers, renderers
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token
from webfront.views import crash_detail, check_new, crash_check, checkin, crash_edit, crash_new, vehicle_new, vehicle_detail, vehicle_edit, person_new, person_detail, person_edit, geo_new, geo_edit, PostListView, PostViewSet, LocateViewSet, ListView, CMVView, PViewset, Personset, VehicleViewset, ProfileViewset, ucfViewset, uc_edit, uce , uv_new, up_new, delete_uc, delete_uv, delete_up, uc_new, audit, chore, ca, va, pa, auditframe, ucfcrash, ucfveh, ucfper, geo_rest, conflicts, cc, cv, cp, reconcile_crash, reconcile_vehicle, reconcile_person, delete_cc, delete_cv, delete_cp, contact

import duo_auth

from .models import Crash, Locate, Vehicle, Person, uc, up, uv, conflict_crash, conflict_vehicle, conflict_person, CrashAudit, VehicleAudit, PersonAudit

 
#basic = PostViewSet.as_view({
#    'get': 'list',
#    'post': 'create'
#})

router = routers.SimpleRouter()
router.register(r'queryfield', PostViewSet)
router.register(r'queryall', PostListView)
router.register(r'queryit', LocateViewSet)
router.register(r'query', ListView)
router.register(r'queryc', CMVView)
router.register(r'pepSPLAJOHKCTZG905A', PViewset)
router.register(r'que', Personset)
router.register(r'veh57RGJI@UBWV4FOCN', VehicleViewset)
router.register(r'pro', ProfileViewset)
router.register(r'r', ucfViewset)

urlpatterns = [
           url(r'^api/', include(router.urls)),
           url(r'^api-token-auth/', obtain_jwt_token),
           url(r'^api-token-auth/', 'rest_framework_jwt.views.obtain_jwt_token'),
           url(r'accounts/duo_login/$', duo_auth.login, name='duo_login'),
           url(r'accounts/duo_logout/$', duo_auth.logout),


#            url(r'^api-token-auth/', obtain_jwt_token),
#            url(r'^restricted/$', RestrictedView.as_view()),
#QC GROUP   
            url(r'^contact/$', contact, name='contact'),
            url(r'^crash/(?P<pk>[0-9]+)/$', crash_detail, name='crash_detail'),
            url(r'^crash/check/new/$', check_new, name='check_new'),
            url(r'^crash/(?P<pk>[0-9]+)/check/$', crash_check, name='crash_check'),
            url(r'^crash/(?P<pk>[0-9]+)/checkin/$', checkin, name='crash_checkin'),
            url(r'^crash/(?P<pk>[0-9]+)/edit/$', crash_edit, name='crash_edit'),
            url(r'^crash/new/$', crash_new, name='crash_new'),
            url(r'^vehicle/new/$', vehicle_new, name='vehicle_new'),
            url(r'^vehicle/(?P<pk>[0-9]+)/$', vehicle_detail, name='vehicle_detail'),
            url(r'^vehicle/(?P<pk>[0-9]+)/edit/$', vehicle_edit, name='vehicle_edit'),
            url(r'^person/new/$', person_new, name='person_new'),
            url(r'^person/(?P<pk>[0-9]+)/$', person_detail, name='person_detail'),
            url(r'^person/(?P<pk>[0-9]+)/edit/$', person_edit, name='person_edit'),
#GIS
            url(r'^g/$',geo_new, name='geo-new'),
            url(r'^g/(?P<pk>[0-9]+)/edit/$', geo_edit, name='geo-edit'),
            url(r'^gup/(?P<pk>[0-9]+)/edit/$', geo_rest, name='geo-rest'),
#UNCONFIRMED
#            url(r'^loc',views.loc.as_view(), name='loc'),
            url(r'^uc/$', uc_new, name='uc-new'),
            url(r'^uc/(?P<pk>[0-9]+)/$', ucfcrash.as_view(), name='uc-detail'),
            url(r'^uc/(?P<pk>[0-9]+)/edit/$', uc_edit, name='uc-edit'),
            url(r'^uce/(?P<pk>[0-9]+)/edit/$', uce, name='uce'),
            url(r'^up/(?P<pk>[0-9]+)/$', ucfper.as_view(), name='up-detail'),
            url(r'^uv/(?P<pk>[0-9]+)/$', ucfveh.as_view(), name='uv-detail'),
            url(r'^uv/new/$', uv_new, name='uv-new'),
            url(r'^up/new/$', up_new, name='up-new'),
#DELETE
            url(r'^delete/(?P<pk>\d+)/uc/$', delete_uc, name='delete_uc'),
            url(r'^delete/(?P<pk>\d+)/uv/$', delete_uv, name='delete_uv'),
            url(r'^delete/(?P<pk>\d+)/up/$', delete_up, name='delete_up'),
	    url(r'^delete/(?P<pk>\d+)/cc/$', delete_cc, name='delete_cc'),
	    url(r'^delete/(?P<pk>\d+)/cv/$', delete_cv, name='delete_cv'),
	    url(r'^delete/(?P<pk>\d+)/cp/$', delete_cp, name='delete_cp'),
#AUDIT
            url(r'^audit/$',audit, name='audit'),
            url(r'^chore/$',chore, name='chore'),
            url(r'^crash/(?P<pk>[0-9]+)/audit/$', ca, name='audit-crash'),
            url(r'^vehicle/(?P<pk>[0-9]+)/audit/$', va, name='audit-vehicle'),
            url(r'^person/(?P<pk>[0-9]+)/audit/$', pa, name='audit-person'),
            url(r'^auditframe/$',auditframe, name='auditframe'),
#Conflicts

            url(r'^conflict/$',conflicts, name='conflict'),
	    url(r'^crash/(?P<pk>[0-9]+)/conflict/$', cc, name='conflict-crash'),
	    url(r'^vehicle/(?P<pk>[0-9]+)/conflict/$', cv, name='conflict-vehicle'),
	    url(r'^person/(?P<pk>[0-9]+)/conflict/$', cp, name='conflict-person'),

    	    url(r'^rc/(?P<pk>[0-9]+)/edit/$', reconcile_crash, name='reconcile_crash'),
            url(r'^rv/(?P<pk>[0-9]+)/edit/$', reconcile_vehicle, name='reconcile_vehicle'),
	    url(r'^rp/(?P<pk>[0-9]+)/edit/$', reconcile_person, name='reconcile_person'),



#            format_suffix_patterns([
#                url(r'^api/', api_root),
#                url(r'queryfield', basic, name='queryfield'),
#            ])
            ]
#urlpatterns = format_suffix_patterns(urlpatterns)

webfront/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MinValueValidator, MaxValueValidator
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight
from django.utils import timezone
from audit_log.models.fields import LastUserField, LastSessionKeyField
from audit_log.models.managers import AuditLog
LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted((item, item) for item in get_all_styles())

# Create your models here.
def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

    # Create your models here.
class SignUp(models.Model):
    email = models.EmailField()
    full_name = models.CharField(max_length=50,default='',blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    def __unicode__(self): #Python 3.3 is__str__
        return self.email

class Crash(models.Model):
    Checkout = models.NullBooleanField(default=False,blank=True)
#    user = LastUserField()
    Assigned = models.CharField(max_length=20,null=True, blank=True)
    ID = models.AutoField(primary_key=True)
    PS_case = models.BigIntegerField(null=True)
    PS_Case_ID = models.CharField(max_length=20,null=True)
    DLD =  models.CharField(max_length=20,null=True, blank=True)
    Validated = models.CharField(max_length=20,null=True)
    Date = models.CharField(max_length=18, blank=True, null=True)
    Date_of_Crash =  models.DateTimeField( blank=True, null=True)
    County_Code = models.CharField(max_length=6,null=True, blank=True)
    Route = models.CharField(max_length=6,null=True, blank=True)
    Direction = models.CharField(max_length=1,null=True, blank=True)
    Milepoint = models.CharField(max_length=8,null=True, blank=True)
    Crash_Verified = models.NullBooleanField(default=False, blank=True)
    City = models.CharField(max_length=20,null=True, blank=True)
    Exit_Number = models.IntegerField(validators=[MaxValueValidator(999)], null=True,  blank=True)
    Type = models.CharField(max_length=2, null=True,blank=True)
    Ramp_ID = models.CharField(max_length=4,null=True, blank=True)
    Case_Number = models.CharField(max_length=20,null=True, blank=True)
    Crash_Severity = models.IntegerField(validators=[MaxValueValidator(89)],null=True,blank=True)
    Nearest_City = models.CharField(max_length=25,null=True, blank=True)
    Distance = models.IntegerField(validators=[MaxValueValidator(5000)], null=True, blank=True)
    Manner_Collision = models.CharField(max_length=2,null=True, blank=True)
    Main_Road_Name = models.CharField(max_length=60,null=True, blank=True)
    Road_Junction_Feature = models.IntegerField(validators=[MaxValueValidator(99)],null=True, blank=True)
    Road_Jurisdiction = models.IntegerField(validators=[MaxValueValidator(99)], null=True, blank=True)
    At_Intersection_With = models.CharField(max_length=25,null=True, blank=True)
    First_Harmful_Event = models.CharField(max_length=2,null=True, blank=True)
    Not_at_Intersection_Distance = models.CharField(max_length=8,null=True, blank=True)
    Not_at_Intersection_Direction = models.CharField(max_length=2,null=True, blank=True)
    Nearest_Intersection = models.CharField(max_length=25,null=True, blank=True)
    Ref_Post_Distance = models.CharField(max_length=8,null=True, blank=True)
    Ref_Post_Direction = models.CharField(max_length=2,null=True, blank=True)
    Ref_Post_Description = models.CharField(max_length=25,null=True, blank=True)
    Light_Condition = models.CharField(max_length=2,null=True, blank=True)
    Weather_Condition = models.CharField(max_length=2,null=True, blank=True)
    Road_Surface_Condition = models.CharField(max_length=2,null=True, blank=True)
    Work_Zone_Related = models.CharField(max_length=2,blank=True, null=True)
    Work_Zone_Worker_Present = models.CharField(max_length=2,blank=True, null=True)
    Work_Zone_ID = models.IntegerField(validators=[MaxValueValidator(99)], null=True, blank=True)
    Work_Zone_Location = models.IntegerField(validators=[MaxValueValidator(99)], null=True, blank=True)
    Unconfirmed_Fatality_Report = models.CharField(max_length=4,null=True)
    Private_Property = models.CharField(max_length=5, null=True, blank=True)
    Narrative = models.TextField(null=True, blank=True)
    QC_Comments = models.TextField(null=True, blank=True)
    Motor_Carrier_Involved = models.CharField(max_length=1,null=True, blank=True)
    CMV_Verified = models.NullBooleanField(default=False, blank=True)
#    session = LastSessionKeyField()
    created_date = models.DateTimeField(null=True,
            default=timezone.now)
    published_date = models.DateTimeField(null=True,
            blank=True)
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return self.PS_Case_ID

class Vehicle(models.Model):
    ID = models.AutoField(primary_key=True)
    PS_case = models.BigIntegerField()
    Vehicle_Number = models.IntegerField(null=True)
    Vin_Verified = models.CharField(max_length=2,null=True,blank=True)
    Vin =  models.CharField(max_length=40,null=True,blank=True)
    License_Plate_Number = models.CharField(max_length=15,null=True,blank=True )
    License_Plate_State = models.CharField(max_length=20,null=True,blank=True)
    Motor_Vehicle_Body_Type = models.CharField(max_length=2,null=True,blank=True)
    Trailing_Units = models.CharField(max_length=2,null=True,blank=True)
    Cargo_Body_Type = models.CharField(max_length=2,null=True,blank=True)
    Special_Function_Code = models.CharField(max_length=2,null=True,blank=True)
    First_Event = models.CharField(max_length=2,null=True,blank=True)
    Second_Event = models.CharField(max_length=2,null=True,blank=True)
    Third_Event = models.CharField(max_length=2,null=True,blank=True)
    Fourth_Event = models.CharField(max_length=2,null=True,blank=True)
    Roadway_Description = models.CharField(max_length=2,null=True,blank=True)
    Disposition_Of_Vehicle = models.CharField(max_length=20,null=True,blank=True)
    Towed_By = models.CharField(max_length=25,null=True,blank=True)
    Carrier_Name = models.CharField(max_length=64,null=True,blank=True)
    US_DOT_Number = models.CharField(max_length=15,null=True,blank=True)
    US_DOT_Verified = models.CharField(max_length=1,null=True,blank=True)
    GCWR_GVWR = models.CharField(max_length=2,null=True,blank=True)
    Carrier_Address_Street = models.CharField(max_length=40,null=True,blank=True)
    Carrier_Address_Street2 = models.CharField(max_length=40,null=True,blank=True)
    Carrier_Address_City = models.CharField(max_length=25,null=True,blank=True)
    Carrier_Address_State = models.CharField(max_length=2,null=True,blank=True)
    Carrier_Address_Zip = models.CharField(max_length=12,null=True,blank=True)
    Carrier_Address_County = models.CharField(max_length=3,null=True,blank=True)
    Carrier_Address_Phone = models.CharField(max_length=25,null=True,blank=True)
    Is_Driver_Carrier = models.CharField(max_length=1,null=True,blank=True)
    Interstate = models.CharField(max_length=1,null=True,blank=True)
    Cargo_Code = models.CharField(max_length=2,null=True,blank=True)
    Hazmat_Released = models.CharField(max_length=1,null=True,blank=True)
    Hazmat_Placard_Number = models.CharField(max_length=20,null=True,blank=True)
    Is_Owner_Driver = models.CharField(max_length=1,null=True,blank=True)
    Owner_First = models.CharField(max_length=20,null=True,blank=True)
    Owner_Middle = models.CharField(max_length=20,null=True,blank=True)
    Owner_Last = models.CharField(max_length=20,null= True,blank=True)
    Owner_Address_Street = models.CharField(max_length=40,null=True,blank=True)
    Owner_Address_Street2 = models.CharField(max_length=40,null=True,blank=True)
    Owner_Address_City = models.CharField(max_length=25,null=True,blank=True)
    Owner_Address_State = models.CharField(max_length=2,null=True,blank=True)
    Owner_Address_Zip = models.CharField(max_length=12,null=True,blank=True)
    Owner_Phone = models.CharField(max_length=25,null=True,blank=True)
    Vehicle_ID = models.IntegerField(null=True,blank=True)
    Make = models.CharField(max_length=15,null=True,blank=True)
    Year = models.CharField(max_length=4,null=True,blank=True)
    Vehicle_Model = models.CharField(max_length=15,null=True,blank=True)
    Travel_Direction = models.IntegerField(validators=[MaxValueValidator(99)], null=True)
    Vehicle_Maneuver = models.IntegerField(validators=[MaxValueValidator(99)], null=True)
    Traffic_Control_Device = models.IntegerField(validators=[MaxValueValidator(99)], null=True)
    Driver_Condition = models.IntegerField(validators=[MaxValueValidator(99)], null=True)
    created_date = models.DateTimeField(null=True,
            default=timezone.now)
    published_date = models.DateTimeField(null=True,
            blank=True)
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return self.PS_case
    
class Person(models.Model):
#  title = models.CharField(max_length=200)
    ID = models.AutoField(primary_key=True)
    PS_case = models.BigIntegerField(null=True)
    Name_Last = models.CharField(max_length=25,null=True,blank=True)
    Name_First = models.CharField(max_length=25,null=True,blank=True)
    Name_Middle = models.CharField(max_length=25,null=True,blank=True)
    Sex = models.CharField(max_length=1,null=True, blank=True)
    Date_Of_Birth = models.CharField(max_length = 10, blank=True, null=True)

webfront/templates/checkout.html
{% load crispy_forms_tags %}
<head>
  <title>Checkout Record</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
    {% include 'head_css.html' %}
    {% include 'navbar.html' %}


<body>

<div class="col-sm-12 container">

<form class="form-inline" method="post" action=''><input type='hidden' name='csrfmiddlewaretoken' value='DlBoh5EcbFn8d3ldIPyhQ0y0ox1pjDnT' />{% csrf_token %}

<div id="div_id_PS_case" class="form-group"> <label for="id_PS_case" class="control-label  requiredField">
                PS case<span class="asteriskField">*</span> </label> <div class="controls "> <input class="numberinput form-control" id="id_PS_case" max="9223372036854775807" min="-9223372036854775808" name="PS_case" type="number" value="{{data}}" /> </div> </div>

<div id="div_id_Checkout" class="form-group"> <label for="id_Checkout" class="control-label ">
               Check Out Crash Record
            </label> <div class="controls "> <select class="nullbooleanselect form-control" id="id_Checkout" name="Checkout" >

{% if instance.Checkout == True %}
<option value="1">No</option>
<option value="2">Yes</option>
{% else %}
<option value="2">Yes</option>
<option value="1">No</option>
{% endif %}

</select> </div> </div>


<input class='btn btn-default' type='submit' value ='Submit' />

</form>  
    



</div>
<br />
<br />
<p class="text-danger"><h3>To view or edit a record, please proceed using the checkout button above.</h3></p> 



</script>  

<style>
tr {
  background: #fff;
  color: #000000;
}
tr:hover {
     background: #f5f5f5;
     cursor: pointer;
}
tr:active {
     background: #808080;
     cursor: pointer;
}

</style>

webfront/templates/chore.html
<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 12px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myUL {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

#myUL li a {
  border: 1px solid #ddd;
  margin-top: -1px; /* Prevent double borders */
  background-color: #f6f6f6;
  padding: 12px;
  text-decoration: none;
  font-size: 18px;
  color: black;
  display: block
}

#myUL li a.header {
  background-color: #e2e2e2;
  cursor: default;
}

#myUL li a:hover:not(.header) {
  background-color: #eee;
}
</style>
</head>
<body>

<h2>Audit Tables</h2>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">

<ul id="myUL">
  <li><a href="" class="header">Crash Records</a></li>
  <li><a href='#'><table><thead><th>Analyst</th><th>PS Case</th><th>Updated Date</th><th>Updated Fields</th></thead></table></a></li>

{% if queryset %}
  {% for instance in queryset %}

  <li><a href="#" ><td>  {{instance.user_id}}</td><td> {{instance.PS_case}}</td><td> {{instance.UpdatedTime}}</td><td>:</td>

{% if instance.Date_of_Crash_OLD != instance.Date_of_Crash %}
<td> Date of Crash</td>
{% endif %}

{% if instance.County_Code_OLD != instance.County_Code %}
<td> County Code</td>
{% endif %}

{% if instance.Exit_Number_OLD != instance.Exit_Number %}
<td> Exit Number</td>
{% endif %}

{% if instance.Ramp_ID_OLD != instance.Ramp_ID %}
<td> Distance</td>
{% endif %}

{% if instance.Crash_Severity_OLD != instance.Crash_Severity %}
<td> Crash Severity</td>
{% endif %}

{% if instance.Nearest_City_OLD != instance.Nearest_City %}
<td> Nearest City</td>
{% endif %}

{% if instance.Distance_OLD != instance.Distance %}
<td> Distance</td>
{% endif %}

{% if instance.Manner_Collision_OLD != instance.Manner_Collision %}
<td> Manner of Collision</td>
{% endif %}

{% if instance.Main_Road_Name_OLD != instance.Main_Road_Name %}
<td> Main Road Name</td>
{% endif %}

{% if instance.Road_Junction_Feature_OLD != instance.Road_Junction_Feature %}
<td> Road Junction Feature</td>
{% endif %}

{% if instance.At_Intersection_With_OLD != instance.At_Intersection_With %}
<td> At Interestion With</td>
{% endif %}

{% if instance.First_Harmful_Event_OLD != instance.First_Harmful_Event %}
<td> First Harmful Event</td>
{% endif %}

{% if instance.Not_At_Intersection_Distance_OLD != instance.Not_At_Intersection_Distance %}
<td> Not At Intersection Distance</td>
{% endif %}

{% if instance.Nearest_Intersection_OLD != instance.Nearest_Intersection %}
<td> Nearest Intersection</td>
{% endif %}

{% if instance.Ref_Post_Distance_OLD != instance.Ref_Post_Distance %}
<td> Ref Post Distance</td>
{% endif %}

{% if instance.Ref_Post_Direction_OLD != instance.Ref_Post_Direction %}
<td> Ref Post Direction</td>
{% endif %}

{% if instance.Ref_Post_Description_OLD != instance.Ref_Post_Description %}
<td> Ref Post Description</td>
{% endif %}

{% if instance.Work_Zone_Related_OLD != instance.Work_Zone_Related %}
<td> Work Zone Related</td>
{% endif %}

{% if instance.Work_Zone_Worker_Present_OLD != instance.Work_Zone_Worker_Present %}
<td> Work Zone Worker Present</td>
{% endif %}

{% if instance.Work_Zone_ID_OLD != instance.Work_Zone_ID %}
<td> Work Zone ID</td>
{% endif %}

{% if instance.Work_Zone_Location_OLD != instance.Work_Zone_Location %}
<td> Work Zone Location</td>
{% endif %}

{% if instance.Unconfirmed_Fatality_Report_OLD != instance.Unconfirmed_Fatality_Report %}
<td> Unconfirmed Fatality Report</td>
{% endif %}

{% if instance.Light_Condition_OLD != instance.Light_Condition %}
<td> Light Condition</td>
{% endif %}

{% if instance.Road_Surface_Condition_OLD != instance.Road_Surface_Condition %}
<td> Road Surface Condition</td>
{% endif %}

{% if instance.Weather_Condition_OLD != instance.Weather_Condition %}
<td> Weather Condition</td>
{% endif %}
</a></li>
  {% endfor %}
{% endif %}



  <li><a href="#" class="header">B</a></li>
  <li><a href="#">Billy</a></li>
  <li><a href="#">Bob</a></li>

  <li><a href="#" class="header">C</a></li>
  <li><a href="#">Calvin</a></li>
  <li><a href="#">Christina</a></li>
  <li><a href="#">Cindy</a></li>
</ul>

<script>
function myFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";

        }
    }
}
</script>

</body>
</html>